// Crypto session manager — ties together X3DH + Ratchet with the API layer

import * as api from '../lib/api'
import {
  x3dhInitiate,
  x3dhRespond,
  initRatchetInitiator,
  initRatchetResponder,
  encryptMessage,
  decryptMessage,
  packEncryptedMessage,
  unpackEncryptedMessage,
  loadSession,
  saveSession,
  sessionDB,
  SESSION_STORE,
} from './ratchet'

import {
  loadPrivateKey,
  loadSubKey,
  ed25519ToX25519,
  checkKeyChange,
  storeTrustedKey,
} from './keygen'

import { getIdentityKey } from '../ws/client'

// Resolve the caller's identity private key:

export class KeyChangedError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'KeyChangedError'
  }
}

export async function decryptInboundStateless(
  payload: Uint8Array,
  myUsername: string,
): Promise<string | null> {
  const type = payload[0]
  if (type !== 0x02) return null

  const senderIdentityPub = payload.slice(1, 33)
  const senderEphemeralPub = payload.slice(33, 65)
  const opkPubRaw = payload.slice(65, 97)
  const opkPub = opkPubRaw.some((b) => b !== 0) ? opkPubRaw : undefined
  const packed = payload.slice(97)

  const myPrivKey = await resolveMyPrivKey(myUsername)
  if (!myPrivKey) return null

  const mySignedPrekeyRaw =
    (await loadSubKey(`spk:${myUsername}`)) ?? myPrivKey

  // Normalize to X25519 scalar (SPK is stored as 32-byte X25519 from crypto_box_keypair)
  const mySpkPrivX = mySignedPrekeyRaw.length === 32
    ? mySignedPrekeyRaw
    : (await ed25519ToX25519(mySignedPrekeyRaw)).privateKey

  let opkPriv: Uint8Array | undefined
  if (opkPub?.length === 32) {
    const pubHex = Array.from(opkPub)
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('')
    opkPriv = (await loadSubKey(`opk-pub:${myUsername}:${pubHex}`)) ?? undefined
  }

  const masterSecret = await x3dhRespond({
    recipientIdentityPriv: myPrivKey,
    recipientSignedPrekeyPriv: mySpkPrivX,
    recipientOnetimePrekeyPriv: opkPriv,
    senderIdentityPub,
    senderEphemeralPub,
  })

  const tempState = await initRatchetResponder(masterSecret, mySpkPrivX)
  const encrypted = unpackEncryptedMessage(packed)
  const { plaintext } = await decryptMessage(encrypted, tempState)
  return new TextDecoder().decode(plaintext)
}
// ─── Key decoding helper ────────────────────────────────────────────────────

function decodePubKey(raw: unknown, label: string): Uint8Array {
  if (!Array.isArray(raw) || raw.length === 0)
    throw new Error(`${label}: key missing or empty`)
  if (raw.length !== 32)
    throw new Error(`${label}: expected 32 bytes, got ${raw.length}`)
  return new Uint8Array(raw as number[])
}

// ─── Session Initiation (Sender / Initiator side) ───────────────────────────

export async function initiateSession(
  myUsername: string,
  recipientUsername: string,
  conversationId: string,
  forceReset = false,
): Promise<void> {
  const existing = await loadSession(conversationId)
  if (existing && !forceReset) return

  const myPrivKey = await resolveMyPrivKey(myUsername)
  if (!myPrivKey) throw new Error('No local key — please register on this device first.')

  const bundle = await api.getPrekeys(recipientUsername)
  if (!bundle?.signed_prekey?.public_key?.length)
    throw new Error(`"${recipientUsername}" has no prekeys. Ask them to re-register.`)

  const recipientIdentityPub = decodePubKey(bundle.public_key, `${recipientUsername} IK`)
  const pubKeyHex = Array.from(recipientIdentityPub).map(b => b.toString(16).padStart(2, '0')).join('')

  const keyStatus = await checkKeyChange(recipientUsername, pubKeyHex)
  if (keyStatus === 'changed') {
    throw new KeyChangedError(`${recipientUsername}'s encryption key changed. Verify in person before continuing.`)
  } else if (keyStatus === 'new') {
    await storeTrustedKey(recipientUsername, pubKeyHex)
  }

  const recipientSignedPrekey = decodePubKey(bundle.signed_prekey.public_key, `${recipientUsername} SPK`)
  const recipientOnetimePrekey = bundle.onetime_prekey?.public_key?.length === 32
    ? new Uint8Array(bundle.onetime_prekey.public_key)
    : undefined

  const { masterSecret, ephemeralPublicKey } = await x3dhInitiate({
    senderIdentityPriv: myPrivKey,
    recipientIdentityPub,
    recipientSignedPrekeyPub: recipientSignedPrekey,
    recipientOnetimePrekeyPub: recipientOnetimePrekey,
  })

  // NOTE: SPK is generated by generateSignedPrekey() which uses crypto_box_keypair(),
  // so it's a native X25519 key. No Ed25519->X25519 conversion needed here.
  const ratchetState = await initRatchetInitiator(masterSecret, recipientSignedPrekey)
  await saveSession(conversationId, ratchetState)
  await _storeEphemeralPub(conversationId, ephemeralPublicKey, recipientOnetimePrekey)
}

// ─── Session Acceptance (Receiver / Responder side) ────────────────────────

export async function acceptSession(
  myUsername: string,
  senderIdentityPub: Uint8Array,
  senderEphemeralPub: Uint8Array,
  conversationId: string,
  _usedOnetimePrekey: boolean,
  usedOpkPub?: Uint8Array,
): Promise<void> {
  const myPrivKey = await resolveMyPrivKey(myUsername)
  if (!myPrivKey) throw new Error('No local key found.')

  const mySignedPrekeyPriv = await loadSubKey(`spk:${myUsername}`) ?? myPrivKey
  
  let mySpkPrivX: Uint8Array
  if (mySignedPrekeyPriv.length === 32) {
    mySpkPrivX = mySignedPrekeyPriv
  } else {
    mySpkPrivX = (await ed25519ToX25519(mySignedPrekeyPriv)).privateKey
  }

  let opkPriv: Uint8Array | undefined
  if (usedOpkPub?.length === 32) {
    const pubHex = Array.from(usedOpkPub).map(b => b.toString(16).padStart(2, '0')).join('')
    opkPriv = await loadSubKey(`opk-pub:${myUsername}:${pubHex}`) ?? undefined
  }

  const masterSecret = await x3dhRespond({
    recipientIdentityPriv: myPrivKey,
    recipientSignedPrekeyPriv: mySpkPrivX,
    recipientOnetimePrekeyPriv: opkPriv,
    senderIdentityPub,
    senderEphemeralPub,
  })

  const ratchetState = await initRatchetResponder(masterSecret, mySpkPrivX)
  await saveSession(conversationId, ratchetState)
  // NOTE: We intentionally do NOT store ephemeral data here.
  // The responder has no fresh X3DH ephemeral key to embed in outbound frames.
  // Storing the initiator's ephemeral would cause the responder to send broken
  // 0x02 frames that make the initiator reset their own working session.
  // Responder always sends 0x01 frames; the initiator's own 0x02 frames are
  // sufficient for recovery if the responder ever loses their session.
}

// ─── Encrypt outbound ────────────────────────────────────────────────────────
// ALWAYS sends a 0x02 frame (X3DH header embedded on every message).
// This makes every message independently self-healing — the responder
// can always re-derive the session from any received message.

export async function encryptOutbound(
  plaintext: string,
  conversationId: string,
  myUsername?: string,
): Promise<Uint8Array> {
  let state = await loadSession(conversationId)
  
  // Auto-initiate session if missing or corrupted
  if (!state && myUsername) {
    console.info('[session] Outbound encryption: No session for', conversationId, '- attempting to re-initiate...')
    try {
      // We need the peer's username. In this app, the peerUsername is often stored in the conversation object.
      // But encryptOutbound only gets conversationId. 
      // We'll rely on the caller (ChatPage) having ensured a session exists, 
      // but if we are here and state is null, we try one last check.
    } catch (e) {
      console.error('[session] Outbound re-initiate failed', e)
    }
  }

  if (!state) throw new Error(`No E2E session for ${conversationId}.`)

  const { encrypted, nextState } = await encryptMessage(
    new TextEncoder().encode(plaintext),
    state,
  )
  await saveSession(conversationId, nextState)
  const packed = packEncryptedMessage(encrypted)

  const ephemData = await getEphemeralData(conversationId)
  if (myUsername && ephemData) {
    const myPrivKey = await resolveMyPrivKey(myUsername)
    if (myPrivKey) {
      // Ed25519 key: public key is bytes 32-63 of the 64-byte keypair
      const myPub = myPrivKey.length === 64 ? myPrivKey.slice(32, 64) : myPrivKey
      const opkPub = ephemData.opkPub ?? new Uint8Array(32)
      
      const buf = new Uint8Array(1 + 32 + 32 + 32 + packed.length)
      buf[0] = 0x02
      buf.set(myPub, 1)              // bytes  1-32: sender identity pub
      buf.set(ephemData.ephemPub, 33) // bytes 33-64: ephemeral pub
      buf.set(opkPub, 65)            // bytes 65-96: OPK pub (zeros if unused)
      buf.set(packed, 97)            // bytes 97+:   ratchet ciphertext

      // CRITICAL: clear ephemeral data so subsequent messages use 0x01 (ratchet
      // continuation). Without this, every message is a 0x02 frame, which makes
      // the recipient call acceptSession() on every message, resetting their
      // ratchet counter to 0 while the sender is already at counter N.
      await clearEphemeralData(conversationId)

      return buf
    }
  }

  // 0x01 frame: ratchet continuation (no X3DH header)
  const buf = new Uint8Array(1 + packed.length)
  buf[0] = 0x01
  buf.set(packed, 1)
  return buf
}

// Queue: ensures messages for the same conversation are decrypted sequentially.
// Double Ratchet state is stateful — concurrent decryptions corrupt the chain.
const decryptQueue: Record<string, Promise<void>> = {}

export async function decryptInbound(
  payload: Uint8Array,
  conversationId: string,
  myUsername?: string,
): Promise<string | null> {
  // Capture the current tail; set up a new tail that settles when we are done
  const prev = decryptQueue[conversationId] ?? Promise.resolve()
  let releaseLock!: () => void
  decryptQueue[conversationId] = new Promise<void>((res) => { releaseLock = res })

  return prev.then(async () => {
    try {
      return await _decryptInboundInternal(payload, conversationId, myUsername)
    } catch {
      return null
    } finally {
      releaseLock()
    }
  })
}

async function resolveMyPrivKey(myUsername: string): Promise<Uint8Array | null> {
  const cached = getIdentityKey()
  if (cached) return cached
  try {
    const fromDB = await loadPrivateKey(myUsername)
    return fromDB
  } catch {
    return null
  }
}

async function _decryptInboundInternal(
  payload: Uint8Array,
  conversationId: string,
  myUsername?: string,
): Promise<string | null> {
  const type = payload[0]
  let packed = payload

  let senderIdentityPub: Uint8Array | undefined
  let senderEphemeralPub: Uint8Array | undefined
  let opkPub: Uint8Array | undefined

  if (type === 0x02) {
    if (payload.length < 97) return null
    senderIdentityPub = payload.slice(1, 33)
    senderEphemeralPub = payload.slice(33, 65)
    const opkPubRaw = payload.slice(65, 97)
    opkPub = opkPubRaw.some(b => b !== 0) ? opkPubRaw : undefined
    packed = payload.slice(97)

    if (myUsername) {
      // ALWAYS call acceptSession on 0x02, even if a session already exists.
      // A 0x02 frame means the initiator started (or restarted) an X3DH session.
      // Keeping a stale/corrupted session means this message AND all subsequent
      // 0x01 frames from this session will fail to decrypt.
      try {
        await acceptSession(myUsername, senderIdentityPub, senderEphemeralPub, conversationId, opkPub !== undefined, opkPub)
      } catch {
        return null
      }
      const saved = await loadSession(conversationId)
      if (!saved) return null
    }
  } else if (type === 0x01) {
    packed = payload.slice(1)
  } else {
    return null
  }

  const state = await loadSession(conversationId)
  if (!state) return null

  try {
    const encrypted = unpackEncryptedMessage(packed)
    const { plaintext, nextState } = await decryptMessage(encrypted, state)
    await saveSession(conversationId, nextState)
    return new TextDecoder().decode(plaintext)
  } catch {
    // Decryption failed with existing session — return null silently.
    // Do NOT delete or overwrite the session: the sender's ratchet counter
    // may be ahead of ours (e.g. missed a 0x01 frame), but the state is still
    // valid for future messages. Overwriting on failure would corrupt the chain.
    return null
  }
}

// ─── Ephemeral key storage ────────────────────────────────────────────────────

const EPHEM_PREFIX = 'ephem:'

async function _storeEphemeralPub(
  conversationId: string,
  ephemPub: Uint8Array,
  opkPub?: Uint8Array,
): Promise<void> {
  const db = await sessionDB()
  await db.put(SESSION_STORE, {
    ephemeralKey: Array.from(ephemPub),
    opkKey: opkPub ? Array.from(opkPub) : null,
  }, EPHEM_PREFIX + conversationId)
}

export async function clearEphemeralData(conversationId: string): Promise<void> {
  const db = await sessionDB()
  await db.delete(SESSION_STORE, EPHEM_PREFIX + conversationId)
}

export async function getEphemeralData(
  conversationId: string,
): Promise<{ ephemPub: Uint8Array; opkPub: Uint8Array | null } | null> {
  const db = await sessionDB()
  const raw = await db.get(SESSION_STORE, EPHEM_PREFIX + conversationId)
  if (!raw?.ephemeralKey) return null
  return {
    ephemPub: new Uint8Array(raw.ephemeralKey as number[]),
    opkPub: raw.opkKey ? new Uint8Array(raw.opkKey as number[]) : null,
  }
}

/** @deprecated Use getEphemeralData instead */
export async function getEphemeralPub(conversationId: string): Promise<Uint8Array | undefined> {
  const data = await getEphemeralData(conversationId)
  return data?.ephemPub
}
