// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (type)
VALUES ($1)
RETURNING id, type, created_at
`

func (q *Queries) CreateConversation(ctx context.Context, type_ string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, type_)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, created_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getConversationsForUser = `-- name: GetConversationsForUser :many
SELECT c.id, c.type, c.created_at
FROM conversations c
JOIN conversation_members cm ON c.id = cm.conversation_id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) GetConversationsForUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT c.id, c.type, c.created_at
FROM conversations c
JOIN conversation_members cm1 ON c.id = cm1.conversation_id AND cm1.user_id = $1
JOIN conversation_members cm2 ON c.id = cm2.conversation_id AND cm2.user_id = $2
WHERE c.type = 'direct'
LIMIT 1
`

type GetDirectConversationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getDirectConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}


