// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID      `json:"group_id"`
	UserID  uuid.UUID      `json:"user_id"`
	Role    sql.NullString `json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) FROM group_members WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, max_members, created_at, conversation_id
`

type CreateGroupParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.Description, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.ConversationID,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, created_by, max_members, created_at, conversation_id FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.ConversationID,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, user_id, role, joined_at FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT u.id, u.username, u.display_name, gm.role, gm.joined_at
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
`

type GetGroupMembersRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Role        sql.NullString `json:"role"`
	JoinedAt    sql.NullTime   `json:"joined_at"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGroupAdmin = `-- name: IsGroupAdmin :one
SELECT EXISTS (
    SELECT 1 FROM group_members
    WHERE group_id = $1
      AND user_id = $2
      AND role = 'admin'
) AS is_admin
`

type IsGroupAdminParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) IsGroupAdmin(ctx context.Context, arg IsGroupAdminParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isGroupAdmin, arg.GroupID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}
