// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_links.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInviteLink = `-- name: CreateInviteLink :one
INSERT INTO invite_links (token, group_id, created_by, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5)
RETURNING token, group_id, created_by, expires_at, max_uses, use_count, revoked, created_at
`

type CreateInviteLinkParams struct {
	Token     string        `json:"token"`
	GroupID   uuid.UUID     `json:"group_id"`
	CreatedBy uuid.NullUUID `json:"created_by"`
	ExpiresAt time.Time     `json:"expires_at"`
	MaxUses   sql.NullInt32 `json:"max_uses"`
}

func (q *Queries) CreateInviteLink(ctx context.Context, arg CreateInviteLinkParams) (InviteLink, error) {
	row := q.db.QueryRowContext(ctx, createInviteLink,
		arg.Token,
		arg.GroupID,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i InviteLink
	err := row.Scan(
		&i.Token,
		&i.GroupID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupInviteLinks = `-- name: GetGroupInviteLinks :many
SELECT token, group_id, created_by, expires_at, max_uses, use_count, revoked, created_at FROM invite_links
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGroupInviteLinks(ctx context.Context, groupID uuid.UUID) ([]InviteLink, error) {
	rows, err := q.db.QueryContext(ctx, getGroupInviteLinks, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteLink{}
	for rows.Next() {
		var i InviteLink
		if err := rows.Scan(
			&i.Token,
			&i.GroupID,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInviteLink = `-- name: GetInviteLink :one
SELECT token, group_id, created_by, expires_at, max_uses, use_count, revoked, created_at FROM invite_links WHERE token = $1
`

func (q *Queries) GetInviteLink(ctx context.Context, token string) (InviteLink, error) {
	row := q.db.QueryRowContext(ctx, getInviteLink, token)
	var i InviteLink
	err := row.Scan(
		&i.Token,
		&i.GroupID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteLinkUseCount = `-- name: IncrementInviteLinkUseCount :exec
UPDATE invite_links
SET use_count = use_count + 1
WHERE token = $1
`

func (q *Queries) IncrementInviteLinkUseCount(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, incrementInviteLinkUseCount, token)
	return err
}

const revokeInviteLink = `-- name: RevokeInviteLink :exec
UPDATE invite_links
SET revoked = TRUE
WHERE token = $1
`

func (q *Queries) RevokeInviteLink(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeInviteLink, token)
	return err
}
