// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredMessages = `-- name: DeleteExpiredMessages :exec
DELETE FROM messages
WHERE ttl_expires_at IS NOT NULL
  AND ttl_expires_at < NOW()
`

func (q *Queries) DeleteExpiredMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMessages)
	return err
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, conversation_id, sender_id, payload, msg_type, timestamp, ttl_expires_at, delivered, created_at FROM messages
WHERE conversation_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type GetMessagesByConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Payload,
			&i.MsgType,
			&i.Timestamp,
			&i.TtlExpiresAt,
			&i.Delivered,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUndeliveredMessages = `-- name: GetUndeliveredMessages :many
SELECT id, conversation_id, sender_id, payload, msg_type, timestamp, ttl_expires_at, delivered, created_at FROM messages
WHERE conversation_id = $1
  AND delivered = FALSE
ORDER BY timestamp ASC
`

func (q *Queries) GetUndeliveredMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getUndeliveredMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Payload,
			&i.MsgType,
			&i.Timestamp,
			&i.TtlExpiresAt,
			&i.Delivered,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, conversation_id, sender_id, payload, msg_type, timestamp, ttl_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, conversation_id, sender_id, payload, msg_type, timestamp, ttl_expires_at, delivered, created_at
`

type InsertMessageParams struct {
	ID             int64         `json:"id"`
	ConversationID uuid.UUID     `json:"conversation_id"`
	SenderID       uuid.NullUUID `json:"sender_id"`
	Payload        []byte        `json:"payload"`
	MsgType        string        `json:"msg_type"`
	Timestamp      time.Time     `json:"timestamp"`
	TtlExpiresAt   sql.NullTime  `json:"ttl_expires_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.Payload,
		arg.MsgType,
		arg.Timestamp,
		arg.TtlExpiresAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Payload,
		&i.MsgType,
		&i.Timestamp,
		&i.TtlExpiresAt,
		&i.Delivered,
		&i.CreatedAt,
	)
	return i, err
}

const markConversationMessagesDelivered = `-- name: MarkConversationMessagesDelivered :exec
UPDATE messages
SET delivered = TRUE
WHERE conversation_id = $1
  AND delivered = FALSE
`

func (q *Queries) MarkConversationMessagesDelivered(ctx context.Context, conversationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markConversationMessagesDelivered, conversationID)
	return err
}

const markMessageDelivered = `-- name: MarkMessageDelivered :exec
UPDATE messages
SET delivered = TRUE
WHERE id = $1
`

func (q *Queries) MarkMessageDelivered(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markMessageDelivered, id)
	return err
}

const purgeOldMessages = `-- name: PurgeOldMessages :exec
DELETE FROM messages
WHERE created_at < NOW() - INTERVAL '3 years'
`

func (q *Queries) PurgeOldMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeOldMessages)
	return err
}
