// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Conversation struct {
	ID        uuid.UUID    `json:"id"`
	Type      string       `json:"type"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ConversationMember struct {
	ConversationID uuid.UUID    `json:"conversation_id"`
	UserID         uuid.UUID    `json:"user_id"`
	JoinedAt       sql.NullTime `json:"joined_at"`
}

type Group struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	CreatedBy      uuid.NullUUID  `json:"created_by"`
	MaxMembers     sql.NullInt32  `json:"max_members"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	ConversationID uuid.NullUUID  `json:"conversation_id"`
}

type GroupMember struct {
	GroupID  uuid.UUID      `json:"group_id"`
	UserID   uuid.UUID      `json:"user_id"`
	Role     sql.NullString `json:"role"`
	JoinedAt sql.NullTime   `json:"joined_at"`
}

type InviteLink struct {
	Token     string        `json:"token"`
	GroupID   uuid.UUID     `json:"group_id"`
	CreatedBy uuid.NullUUID `json:"created_by"`
	ExpiresAt time.Time     `json:"expires_at"`
	MaxUses   sql.NullInt32 `json:"max_uses"`
	UseCount  sql.NullInt32 `json:"use_count"`
	Revoked   sql.NullBool  `json:"revoked"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Message struct {
	ID             int64         `json:"id"`
	ConversationID uuid.UUID     `json:"conversation_id"`
	SenderID       uuid.NullUUID `json:"sender_id"`
	Payload        []byte        `json:"payload"`
	MsgType        string        `json:"msg_type"`
	Timestamp      time.Time     `json:"timestamp"`
	TtlExpiresAt   sql.NullTime  `json:"ttl_expires_at"`
	Delivered      sql.NullBool  `json:"delivered"`
	DeliveredAt    sql.NullTime  `json:"delivered_at"`
	ReadAt         sql.NullTime  `json:"read_at"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

type Payment struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	AmountIdr    int32          `json:"amount_idr"`
	Method       sql.NullString `json:"method"`
	Status       sql.NullString `json:"status"`
	PeriodMonths sql.NullInt32  `json:"period_months"`
	PaidAt       sql.NullTime   `json:"paid_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Prekey struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	KeyType   string       `json:"key_type"`
	PublicKey []byte       `json:"public_key"`
	Signature []byte       `json:"signature"`
	Used      sql.NullBool `json:"used"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PushSubscription struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Endpoint   string         `json:"endpoint"`
	P256dh     string         `json:"p256dh"`
	Auth       string         `json:"auth"`
	UserAgent  sql.NullString `json:"user_agent"`
	CreatedAt  time.Time      `json:"created_at"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
}

type SenderKey struct {
	GroupID     uuid.UUID `json:"group_id"`
	SenderID    uuid.UUID `json:"sender_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
	KeyBlob     []byte    `json:"key_blob"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Session struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	Revoked    sql.NullBool `json:"revoked"`
}

type Upload struct {
	ID          uuid.UUID      `json:"id"`
	UploaderID  uuid.NullUUID  `json:"uploader_id"`
	Filename    sql.NullString `json:"filename"`
	MimeType    sql.NullString `json:"mime_type"`
	SizeBytes   int32          `json:"size_bytes"`
	StoragePath string         `json:"storage_path"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Username      string         `json:"username"`
	DisplayName   sql.NullString `json:"display_name"`
	PublicKey     []byte         `json:"public_key"`
	KeyVersion    sql.NullInt32  `json:"key_version"`
	Tier          sql.NullString `json:"tier"`
	TierExpiresAt sql.NullTime   `json:"tier_expires_at"`
	Discoverable  sql.NullBool   `json:"discoverable"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	LastSeenAt    sql.NullTime   `json:"last_seen_at"`
}
