// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const confirmPayment = `-- name: ConfirmPayment :exec
UPDATE payments
SET status  = 'paid',
    paid_at = NOW()
WHERE id = $1
`

func (q *Queries) ConfirmPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, confirmPayment, id)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, amount_idr, method, period_months)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, amount_idr, method, status, period_months, paid_at, created_at
`

type CreatePaymentParams struct {
	UserID       uuid.NullUUID  `json:"user_id"`
	AmountIdr    int32          `json:"amount_idr"`
	Method       sql.NullString `json:"method"`
	PeriodMonths sql.NullInt32  `json:"period_months"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.UserID,
		arg.AmountIdr,
		arg.Method,
		arg.PeriodMonths,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountIdr,
		&i.Method,
		&i.Status,
		&i.PeriodMonths,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, amount_idr, method, status, period_months, paid_at, created_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountIdr,
		&i.Method,
		&i.Status,
		&i.PeriodMonths,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentsByUser = `-- name: GetPaymentsByUser :many
SELECT id, user_id, amount_idr, method, status, period_months, paid_at, created_at FROM payments
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPaymentsByUser(ctx context.Context, userID uuid.NullUUID) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountIdr,
			&i.Method,
			&i.Status,
			&i.PeriodMonths,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingPayments = `-- name: GetPendingPayments :many
SELECT p.id, p.user_id, p.amount_idr, p.method, p.status, p.period_months, p.paid_at, p.created_at, u.username
FROM payments p
JOIN users u ON u.id = p.user_id
WHERE p.status = 'pending'
ORDER BY p.created_at ASC
`

type GetPendingPaymentsRow struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	AmountIdr    int32          `json:"amount_idr"`
	Method       sql.NullString `json:"method"`
	Status       sql.NullString `json:"status"`
	PeriodMonths sql.NullInt32  `json:"period_months"`
	PaidAt       sql.NullTime   `json:"paid_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Username     string         `json:"username"`
}

func (q *Queries) GetPendingPayments(ctx context.Context) ([]GetPendingPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingPaymentsRow{}
	for rows.Next() {
		var i GetPendingPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountIdr,
			&i.Method,
			&i.Status,
			&i.PeriodMonths,
			&i.PaidAt,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
