// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prekeys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countAvailableOneTimePrekeys = `-- name: CountAvailableOneTimePrekeys :one
SELECT COUNT(*) FROM prekeys
WHERE user_id = $1
  AND key_type = 'onetime'
  AND used = FALSE
`

func (q *Queries) CountAvailableOneTimePrekeys(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableOneTimePrekeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePrekeysByUser = `-- name: DeletePrekeysByUser :exec
DELETE FROM prekeys WHERE user_id = $1
`

func (q *Queries) DeletePrekeysByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePrekeysByUser, userID)
	return err
}

const getAvailablePrekey = `-- name: GetAvailablePrekey :one
SELECT id, user_id, key_type, public_key, signature, used, created_at FROM prekeys
WHERE user_id = $1
  AND key_type = $2
  AND used = FALSE
ORDER BY created_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type GetAvailablePrekeyParams struct {
	UserID  uuid.UUID `json:"user_id"`
	KeyType string    `json:"key_type"`
}

func (q *Queries) GetAvailablePrekey(ctx context.Context, arg GetAvailablePrekeyParams) (Prekey, error) {
	row := q.db.QueryRowContext(ctx, getAvailablePrekey, arg.UserID, arg.KeyType)
	var i Prekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyType,
		&i.PublicKey,
		&i.Signature,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getSignedPrekey = `-- name: GetSignedPrekey :one
SELECT id, user_id, key_type, public_key, signature, used, created_at FROM prekeys
WHERE user_id = $1
  AND key_type = 'signed'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSignedPrekey(ctx context.Context, userID uuid.UUID) (Prekey, error) {
	row := q.db.QueryRowContext(ctx, getSignedPrekey, userID)
	var i Prekey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyType,
		&i.PublicKey,
		&i.Signature,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const insertPrekeys = `-- name: InsertPrekeys :exec
INSERT INTO prekeys (user_id, key_type, public_key, signature)
SELECT $1, $2, unnest($3::bytea[]), unnest($4::bytea[])
`

type InsertPrekeysParams struct {
	UserID  uuid.UUID `json:"user_id"`
	KeyType string    `json:"key_type"`
	Column3 [][]byte  `json:"column_3"`
	Column4 [][]byte  `json:"column_4"`
}

func (q *Queries) InsertPrekeys(ctx context.Context, arg InsertPrekeysParams) error {
	_, err := q.db.ExecContext(ctx, insertPrekeys,
		arg.UserID,
		arg.KeyType,
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
	)
	return err
}

const markPrekeyUsed = `-- name: MarkPrekeyUsed :exec
UPDATE prekeys
SET used = TRUE
WHERE id = $1
`

func (q *Queries) MarkPrekeyUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPrekeyUsed, id)
	return err
}
