// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	ConfirmPayment(ctx context.Context, id uuid.UUID) error
	CountAvailableOneTimePrekeys(ctx context.Context, userID uuid.UUID) (int64, error)
	CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error)
	CreateConversation(ctx context.Context, type_ string) (Conversation, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateInviteLink(ctx context.Context, arg CreateInviteLinkParams) (InviteLink, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSession(ctx context.Context, userID uuid.UUID) (Session, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredMessages(ctx context.Context) error
	DeletePrekeysByUser(ctx context.Context, userID uuid.UUID) error
	GetAvailablePrekey(ctx context.Context, arg GetAvailablePrekeyParams) (Prekey, error)
	GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error)
	GetConversationsForUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error)
	GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (Conversation, error)
	GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupInviteLinks(ctx context.Context, groupID uuid.UUID) ([]InviteLink, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GetGroupMembersRow, error)
	GetInviteLink(ctx context.Context, token string) (InviteLink, error)
	GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]Message, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentsByUser(ctx context.Context, userID uuid.NullUUID) ([]Payment, error)
	GetPendingPayments(ctx context.Context) ([]GetPendingPaymentsRow, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSignedPrekey(ctx context.Context, userID uuid.UUID) (Prekey, error)
	GetUndeliveredMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error)
	GetUploadByID(ctx context.Context, id uuid.UUID) (Upload, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementInviteLinkUseCount(ctx context.Context, token string) error
	IncrementKeyVersion(ctx context.Context, arg IncrementKeyVersionParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	InsertPrekeys(ctx context.Context, arg InsertPrekeysParams) error
	IsGroupAdmin(ctx context.Context, arg IsGroupAdminParams) (bool, error)
	MarkConversationMessagesDelivered(ctx context.Context, conversationID uuid.UUID) error
	MarkMessageDelivered(ctx context.Context, id int64) error
	MarkPrekeyUsed(ctx context.Context, id uuid.UUID) error
	PurgeOldMessages(ctx context.Context) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	RevokeInviteLink(ctx context.Context, token string) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	SearchUsers(ctx context.Context, username string) ([]SearchUsersRow, error)
	UpdateLastSeen(ctx context.Context, id uuid.UUID) error
	UpdateSessionLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) error
}

var _ Querier = (*Queries)(nil)
