// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (uploader_id, filename, mime_type, size_bytes, storage_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uploader_id, filename, mime_type, size_bytes, storage_path, created_at
`

type CreateUploadParams struct {
	UploaderID  uuid.NullUUID  `json:"uploader_id"`
	Filename    sql.NullString `json:"filename"`
	MimeType    sql.NullString `json:"mime_type"`
	SizeBytes   int32          `json:"size_bytes"`
	StoragePath string         `json:"storage_path"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, createUpload,
		arg.UploaderID,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadByID = `-- name: GetUploadByID :one
SELECT id, uploader_id, filename, mime_type, size_bytes, storage_path, created_at FROM uploads WHERE id = $1
`

func (q *Queries) GetUploadByID(ctx context.Context, id uuid.UUID) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUploadByID, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}
