// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, public_key)
VALUES ($1, $2)
RETURNING id, username, display_name, public_key, key_version, tier, tier_expires_at, discoverable, created_at, last_seen_at
`

type CreateUserParams struct {
	Username  string `json:"username"`
	PublicKey []byte `json:"public_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PublicKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PublicKey,
		&i.KeyVersion,
		&i.Tier,
		&i.TierExpiresAt,
		&i.Discoverable,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, public_key, key_version, tier, tier_expires_at, discoverable, created_at, last_seen_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PublicKey,
		&i.KeyVersion,
		&i.Tier,
		&i.TierExpiresAt,
		&i.Discoverable,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, public_key, key_version, tier, tier_expires_at, discoverable, created_at, last_seen_at FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PublicKey,
		&i.KeyVersion,
		&i.Tier,
		&i.TierExpiresAt,
		&i.Discoverable,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const incrementKeyVersion = `-- name: IncrementKeyVersion :exec
UPDATE users
SET key_version  = key_version + 1,
    public_key   = $2
WHERE id = $1
`

type IncrementKeyVersionParams struct {
	ID        uuid.UUID `json:"id"`
	PublicKey []byte    `json:"public_key"`
}

func (q *Queries) IncrementKeyVersion(ctx context.Context, arg IncrementKeyVersionParams) error {
	_, err := q.db.ExecContext(ctx, incrementKeyVersion, arg.ID, arg.PublicKey)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, display_name, discoverable, created_at
FROM users
WHERE username ILIKE $1
  AND discoverable = TRUE
LIMIT 20
`

type SearchUsersRow struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	DisplayName  sql.NullString `json:"display_name"`
	Discoverable sql.NullBool   `json:"discoverable"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, username string) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Discoverable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2,
    discoverable = $3
WHERE id = $1
RETURNING id, username, display_name, public_key, key_version, tier, tier_expires_at, discoverable, created_at, last_seen_at
`

type UpdateUserProfileParams struct {
	ID           uuid.UUID      `json:"id"`
	DisplayName  sql.NullString `json:"display_name"`
	Discoverable sql.NullBool   `json:"discoverable"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Discoverable)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PublicKey,
		&i.KeyVersion,
		&i.Tier,
		&i.TierExpiresAt,
		&i.Discoverable,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateUserTier = `-- name: UpdateUserTier :exec
UPDATE users
SET tier = $2,
    tier_expires_at = $3
WHERE id = $1
`

type UpdateUserTierParams struct {
	ID            uuid.UUID      `json:"id"`
	Tier          sql.NullString `json:"tier"`
	TierExpiresAt sql.NullTime   `json:"tier_expires_at"`
}

func (q *Queries) UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTier, arg.ID, arg.Tier, arg.TierExpiresAt)
	return err
}
